# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torz', '0002_brainsystem_torzbrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainsystem',
            name='query',
            field=models.CharField(default=True, max_length=32),
        ),
    ]
