# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torz', '0003_brainsystem_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainsystem',
            name='knowledge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brainsystem',
            name='query',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='torzbrain',
            name='brain',
            field=models.CharField(max_length=100),
        ),
    ]
